services:
  api:
    build:
      context: ./docker
      dockerfile: Dockerfile-api
    depends_on:
      - database
    environment:
      HTTPS_ALWAYS: 0
      PORT: 3000
      SESSION_SECRET: development-secret
      STORAGE_PATH: /storage
      DB_DATABASE: project_loved
      DB_HOST: database
      DB_PASSWORD: ""
      DB_PORT: 3306
      DB_USER: project_loved
      NODE_ENV: development
    volumes:
      - api_storage:/storage
      - ./bridge:/app/bridge
      - ./server:/app/server

  assets:
    build:
      context: ./docker
      dockerfile: Dockerfile-assets
    volumes:
      - ./bridge:/app/bridge
      - ./client:/app/client

  database:
    build:
      context: ./docker
      dockerfile: Dockerfile-database
    ports:
      - "3306:3306"
    volumes:
      - database:/var/lib/mysql
      - ./server/migrations:/migrations

  nginx:
    image: nginx:latest
    depends_on:
      - api
      - assets
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  api_storage:
  database:
